formcheckLanguage = {
	required: "ទិន្នន័យចាំបាច់ លោកអ្នកត្រូវតែបញ្ចូល ។ Ce champ est obligatoire.",
	alpha: "Ce champ n'accepte que des caract&egrave;res alphab&eacute;tiques sans accents.",
	alphanum: "Ce champ n'accepte que des caract&egrave;res alphanum&eacute;riques.",
	nodigit: "Ce champ n'accepte pas les chiffres.",
	digit: "Ce champ n'accepte que les chiffres.",
	digitmin: "Cette valeur doit &ecirc;tre au minimum %0",
	digitltd: "Cette valeur doit &ecirc;tre comprise entre %0 et %1",
	number: "Ce champ n'accepte qu'un nombre.",
	email: "Veuillez entrer une adresse email valide: <br /><span>Ex. votrenom@domain.com</span>",
	image : 'Ce champ ne peut contenir que des images', 
	phone: "Veuillez entrer un num&eacute;ro de t&eacute;l&eacute;phone valide.",
	url: "Veuillez entrer une adresse de site internet valide: <br /><span>Ex. http://www.domain.com</span>",
	date: "Ce champs doit &ecirc;tre au format jj/mm/aaaa: <br /><span>Ex. 17/03/1986</span>",
	
	confirm: "Ce champ est diff&eacute;rent du champ \"%0\".",
	differs: "Ce champ doit &ecirc;tre diff&eacute;rent du champ \"%0\".",
	length_str: "La longueur doit &ecirc;tre comprise entre %0 et %1 caract&egrave;res.",
	length_fix: "La longueur doit &ecirc;tre de %0 caract&egrave;res exactement.",
	lengthmax: "La longueur doit &ecirc;tre au maximum de %0 caract&egrave;res.",
	lengthmin: "La longueur doit &ecirc;tre au minimum de %0 caract&egrave;res.",
	words_min : "Ce champ doit contenir au moins %0 mots, actuellement : %1 mots",
	words_range : "Ce champ doit contenir entre %0 et %1 mots, actuellement : %2 mots",
	words_max : "Ce champ doit contenir au plus %0 mots, actuellement : %1 mots",
	checkbox: "Veuillez accepter les conditions g&eacute;n&eacute;rales de vente",
	checkboxes_group : 'Merci de cocher au moins %0 case(s)',
	radios: "Merci de choisir une valeur.",
	select: "Merci de choisir une valeur dans la liste.",
	select_multiple: "Merci de choisir au moins une valeur dans la liste."
}